assembly-versioning-scheme: MajorMinorPatch
mode: Mainline

branches:
  master:
    mode: ContinuousDeployment
    regex: master
    tag: dev
    increment: Minor
    is-source-branch-for: ['beta', 'stable']

  pull-request:
    regex: ^(pull|pull\-requests|pr)[/-]
    mode: ContinuousDeployment
    tag: 'PullRequest'
    tag-number-pattern: '[/-](?<number>\d+)[-/]'
    increment: Inherit

  beta:
    mode: ContinuousDeployment
    regex: ^release/beta/.*
    tag: beta
    increment: none
    source-branches: ['master']

  stable:
    regex: ^release/stable/.*
    tag: ''
    increment: Patch
    source-branches: ['master','beta']
    is-mainline: true

  dev:
    mode: ContinuousDeployment
    regex: ^dev/.*?/(.*?)
    #tag: "dev.{BranchName}"
    source-branches: ['master', 'stable']
    increment: none

ignore:
  sha: []